Fix for button click tracking not working
mautic/grapesjs-preset-mautic pull request #14
Opened 2021-08-12 16:54 UTC by adiux

fixes: https://github.com/mautic/mautic/issues/10323

2021-08-13 13:23 UTC, adiux commented
https://github.com/mautic/mautic/issues/10331

2021-08-13 14:41 UTC, RCheesley requested changes, later dismissed
Superficial review for grammar etc.

A few suggestions to make sure the messages we show to users/output to logs are consistent with our style guide. Main things to look for (as some I could not update with this review) are:

- Capitalise the first word
- Capitalise any Mautic features, for example Dynamic Content, and ensure they are written out fully and correctly (a few places have used DynamicContent without a space)
- Capitalise any abbreviations such as HTML and MJML

2021-08-13 14:41 UTC, RCheesley commented on dist/commands.js
> +  }); // Link store to compoennt
```suggestion
  }); // Link store to component
```

2021-08-13 14:41 UTC, RCheesley commented on dist/dynamicContent/dynamicContent.commands.js
> +        this.logger.debug('Expected a dynamic content component', {
```suggestion
        this.logger.debug('Expected a Dynamic Content component', {
```

2021-08-13 14:41 UTC, RCheesley commented on dist/dynamicContent/dynamicContent.commands.js
> +        throw new Error('no dynamic content component');
```suggestion
        throw new Error('No Dynamic Content component');
```

2021-08-13 14:41 UTC, RCheesley commented on dist/dynamicContent/dynamicContent.service.js
> +    this.logger.debug('Created a new dynamic content item in store', {
```suggestion
    this.logger.debug('Created a new Dynamic Content item in store', {
```

2021-08-13 14:41 UTC, RCheesley commented on dist/mjml/mjml.service.js
>          throw new Error('no valid mjml string');
```suggestion
        throw new Error('No valid MJML string');
```

2021-08-13 14:41 UTC, RCheesley commented on dist/buttons/buttonClose.command.js
>        throw new Error('no email-html editor');
```suggestion
      throw new Error('No email-HTML editor');
```

2021-08-13 14:41 UTC, RCheesley commented on dist/buttons/buttonClose.command.js
>        throw new Error('no email-mjml editor');
```suggestion
      throw new Error('No email-MJML editor');
```

2021-08-13 14:41 UTC, RCheesley commented on dist/dynamicContent/dynamicContent.commands.js
> +      this.logger.debug('Replaced components content with its token', {
```suggestion
      this.logger.debug('Replaced component's content with its token', {
```

2021-08-14 08:47 UTC, dennisameling approved these changes
Looks good to me! Appreciate the comments in the code so that it's easier for future contributors to see what's going on 👍🏼

2021-08-14 08:48 UTC, merged